<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UseWindowsForms>false</UseWindowsForms>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <RootNamespace>cscheat</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Swed64" Version="1.0.5" />
    <PackageReference Include="GameOverlay.Net" Version="4.3.0" />
  </ItemGroup>
</Project>
